In [23]:
import numpy as np

In [24]:
import pandas as pd

In [25]:
grades = {"atil":50,"james":60,"lars":70}

In [26]:
pd.Series(grades)

atil     50
james    60
lars     70
dtype: int64

In [27]:
names = ["atil","james","lars"]
grades =[50,60,70]

In [28]:
pd.Series(grades)

0    50
1    60
2    70
dtype: int64

In [29]:
pd.Series(names)

0     atil
1    james
2     lars
dtype: object

In [30]:
pd.Series(names,grades)

50     atil
60    james
70     lars
dtype: object

In [31]:
# WITH NUMPY

In [32]:
numpy_array = np.array([50,60,70,80])

In [33]:
pd.Series(numpy_array)

0    50
1    60
2    70
3    80
dtype: int64

In [34]:
# ARITMATIC

In [35]:
# YARISMA YAPILSIN VE ELIMIZDE YARISMA SONUCLARI OLSUN

In [36]:
contest_result = pd.Series( data = [50,60,70] , index = ["james","atil","lars"] )

In [37]:
contest_result2 = pd.Series( data=[20,50,10],  index =  ["james","atil","lars"])

In [38]:
contest_result

james    50
atil     60
lars     70
dtype: int64

In [39]:
contest_result2

james    20
atil     50
lars     10
dtype: int64

In [40]:
contest_result["atil"]

np.int64(60)

In [41]:
final_result = contest_result + contest_result2

In [42]:
final_result

james     70
atil     110
lars      80
dtype: int64

In [43]:
diffirent_series = pd.Series([20,30,40,50],["a","b","c","d"])

In [44]:
diffirent_series2 = pd.Series([20,30,40,50],["a","c","f","g"])

In [45]:
final_series2 = diffirent_series2 + diffirent_series

In [46]:
final_series2

a    40.0
b     NaN
c    70.0
d     NaN
f     NaN
g     NaN
dtype: float64

In [47]:
# goruldugu uzere olan indexleri topladi olmayanlari nan seklinde gosterdi

In [48]:
## DATAFRAME ( COK ONEMI)

In [49]:
data = np.random.randn(4,3)

In [50]:
data

array([[ 0.48590236, -0.53733136, -0.29495262],
       [ 0.55427665,  1.14852103, -0.25596983],
       [ 1.24108296, -0.25154026, -0.2424182 ],
       [-0.03420991, -0.55508249, -1.64784648]])

In [51]:
data_frame = pd.DataFrame(data)

In [52]:
data_frame # bir nevi bize tabloyu seklinde veriyi sunar

          0         1         2
0  0.485902 -0.537331 -0.294953
1  0.554277  1.148521 -0.255970
2  1.241083 -0.251540 -0.242418
3 -0.034210 -0.555082 -1.647846

In [53]:
type(data_frame)

pandas.core.frame.DataFrame

In [54]:
type(data_frame[0])

pandas.core.series.Series

In [55]:
new_df = pd.DataFrame(data,index = ["atil","zeynep","atlas","mehmet",],columns = ["salary","age","sanirotiy"])

In [56]:
new_df

          salary       age  sanirotiy
atil    0.485902 -0.537331  -0.294953
zeynep  0.554277  1.148521  -0.255970
atlas   1.241083 -0.251540  -0.242418
mehmet -0.034210 -0.555082  -1.647846

In [57]:
new_df["age"]

atil     -0.537331
zeynep    1.148521
atlas    -0.251540
mehmet   -0.555082
Name: age, dtype: float64

In [58]:
new_df["salary"]

atil      0.485902
zeynep    0.554277
atlas     1.241083
mehmet   -0.034210
Name: salary, dtype: float64

In [59]:
new_df.loc["atil"] # eger tablomuzda row getirmek istersek loc komutunu kullaniriz

salary       0.485902
age         -0.537331
sanirotiy   -0.294953
Name: atil, dtype: float64

In [60]:
new_df.iloc[0] # eger indexe gore tablodan veri cekmek istersek o zaman iloc komutunu kullaniriz

salary       0.485902
age         -0.537331
sanirotiy   -0.294953
Name: atil, dtype: float64

In [61]:
new_df.iloc[-1]

salary      -0.034210
age         -0.555082
sanirotiy   -1.647846
Name: mehmet, dtype: float64

In [62]:
new_df.iloc[:,1]  # burada : tum row sec demek virgulden sonraki de hangi index getirmek istedigimizi koda soyler bizimi icin

atil     -0.537331
zeynep    1.148521
atlas    -0.251540
mehmet   -0.555082
Name: age, dtype: float64

In [63]:
# DATALARI MANIPULE ETME

In [64]:
new_df["extra"] = 10

In [65]:
new_df

          salary       age  sanirotiy  extra
atil    0.485902 -0.537331  -0.294953     10
zeynep  0.554277  1.148521  -0.255970     10
atlas   1.241083 -0.251540  -0.242418     10
mehmet -0.034210 -0.555082  -1.647846     10

In [66]:
new_df.drop("extra",axis=1)

          salary       age  sanirotiy
atil    0.485902 -0.537331  -0.294953
zeynep  0.554277  1.148521  -0.255970
atlas   1.241083 -0.251540  -0.242418
mehmet -0.034210 -0.555082  -1.647846

In [67]:
new_df # sildik ama hala extra kolonu bizimle geliyor bunu duzeltmek icin asagidaki gibi komutu yazmamiz gerekir

          salary       age  sanirotiy  extra
atil    0.485902 -0.537331  -0.294953     10
zeynep  0.554277  1.148521  -0.255970     10
atlas   1.241083 -0.251540  -0.242418     10
mehmet -0.034210 -0.555082  -1.647846     10

In [68]:
new_df.drop("extra",axis = 1,inplace = True ) # eger row silmek istersek axis = 1 seklinde belirmtmemiz gerekir ama sadece sutun sileceksek o zaman axis =1 seklinde belirtme yapmamiza gerek yoktur

In [69]:
new_df # bu sekilde extra sutununu tamamen kaldirmis oluruz

          salary       age  sanirotiy
atil    0.485902 -0.537331  -0.294953
zeynep  0.554277  1.148521  -0.255970
atlas   1.241083 -0.251540  -0.242418
mehmet -0.034210 -0.555082  -1.647846

In [70]:
new_df.drop("mehmet",axis = 0)

          salary       age  sanirotiy
atil    0.485902 -0.537331  -0.294953
zeynep  0.554277  1.148521  -0.255970
atlas   1.241083 -0.251540  -0.242418

In [71]:
new_df.drop("mehmet")

          salary       age  sanirotiy
atil    0.485902 -0.537331  -0.294953
zeynep  0.554277  1.148521  -0.255970
atlas   1.241083 -0.251540  -0.242418

In [72]:
# yukarida goruldugu uzere ikisiside bize ayni sonucu verdi bundan dolayi columns silerken axis = 0 seklinde belirtmeye gerek yoktur

In [73]:
new_df.loc["atlas"]["salary"]

np.float64(1.2410829631146896)

In [74]:
new_df.loc["atlas","salary"]

np.float64(1.2410829631146896)

In [75]:
# mehmetin maasini degistermek isteyelim

In [76]:
new_df.loc["mehmet","salary"] = 100

In [77]:
new_df

            salary       age  sanirotiy
atil      0.485902 -0.537331  -0.294953
zeynep    0.554277  1.148521  -0.255970
atlas     1.241083 -0.251540  -0.242418
mehmet  100.000000 -0.555082  -1.647846

In [78]:
# 0 dan buyuk olanlari gormek istersek

In [79]:
new_df  > 0

        salary    age  sanirotiy
atil      True  False      False
zeynep    True   True      False
atlas     True  False      False
mehmet    True  False      False

In [80]:
new_df<0

        salary    age  sanirotiy
atil     False   True       True
zeynep   False  False       True
atlas    False   True       True
mehmet   False   True       True

In [81]:
new_df[new_df > 0 ]

            salary       age  sanirotiy
atil      0.485902       NaN        NaN
zeynep    0.554277  1.148521        NaN
atlas     1.241083       NaN        NaN
mehmet  100.000000       NaN        NaN

In [82]:
# kolona ozel buyuk yada kucuk degerleri gormek istersek

In [83]:
new_df["salary"] > 1

atil      False
zeynep    False
atlas      True
mehmet     True
Name: salary, dtype: bool

In [84]:
new_df[new_df["salary"] > 1 ]

            salary       age  sanirotiy
atlas     1.241083 -0.251540  -0.242418
mehmet  100.000000 -0.555082  -1.647846

In [85]:
# dataframe ile index degistirme

In [86]:
new_df.reset_index()

    index      salary       age  sanirotiy
0    atil    0.485902 -0.537331  -0.294953
1  zeynep    0.554277  1.148521  -0.255970
2   atlas    1.241083 -0.251540  -0.242418
3  mehmet  100.000000 -0.555082  -1.647846

In [87]:
reset_frame = new_df.reset_index()

In [88]:
reset_frame

    index      salary       age  sanirotiy
0    atil    0.485902 -0.537331  -0.294953
1  zeynep    0.554277  1.148521  -0.255970
2   atlas    1.241083 -0.251540  -0.242418
3  mehmet  100.000000 -0.555082  -1.647846

In [89]:
new_indices= ["atil","ati","zey","meh"]

In [90]:
new_df["newindex"] = new_indices

In [91]:
new_df # yansimadi cunku true kodunu eklemedik kodumuzua

            salary       age  sanirotiy newindex
atil      0.485902 -0.537331  -0.294953     atil
zeynep    0.554277  1.148521  -0.255970      ati
atlas     1.241083 -0.251540  -0.242418      zey
mehmet  100.000000 -0.555082  -1.647846      meh

In [92]:
new_df.set_index("newindex", inplace = True )

In [93]:
new_df

              salary       age  sanirotiy
newindex
atil        0.485902 -0.537331  -0.294953
ati         0.554277  1.148521  -0.255970
zey         1.241083 -0.251540  -0.242418
meh       100.000000 -0.555082  -1.647846

In [94]:
# MULTI INDEX ( BIRDEN FAZLA INDEX )

In [95]:
first_index = [ "Simson","Simson","Simson","south park","south park","south park"]

In [96]:
inner_index = ["homer","bart","marge","cartman","kenny","kyle"]

In [97]:
zipped_index = list(zip(first_index,inner_index))

In [98]:
zipped_index

[('Simson', 'homer'),
 ('Simson', 'bart'),
 ('Simson', 'marge'),
 ('south park', 'cartman'),
 ('south park', 'kenny'),
 ('south park', 'kyle')]

In [99]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [100]:
zipped_index

MultiIndex([(    'Simson',   'homer'),
            (    'Simson',    'bart'),
            (    'Simson',   'marge'),
            ('south park', 'cartman'),
            ('south park',   'kenny'),
            ('south park',    'kyle')],
           )

In [101]:
sample_values = np.ones((6,2))

In [102]:
big_df = pd.DataFrame(sample_values,index=zipped_index , columns = ["age","salary"])

In [103]:
big_df

                    age  salary
Simson     homer    1.0     1.0
           bart     1.0     1.0
           marge    1.0     1.0
south park cartman  1.0     1.0
           kenny    1.0     1.0
           kyle     1.0     1.0

In [104]:
big_df["age"]

Simson      homer      1.0
            bart       1.0
            marge      1.0
south park  cartman    1.0
            kenny      1.0
            kyle       1.0
Name: age, dtype: float64

In [105]:
big_df.loc["Simson"]

       age  salary
homer  1.0     1.0
bart   1.0     1.0
marge  1.0     1.0

In [106]:
# en icdeki veriyi cagirmak icin distan ice dogru gitmemiz lazim

In [107]:
big_df.loc["Simson"].loc["homer"]

age       1.0
salary    1.0
Name: homer, dtype: float64

In [108]:
# PANDAS ILE ILGI ONEMLI ORNEKLER

In [109]:
import pandas as pd
import numpy as np

In [110]:
weather_df = pd.read_excel(r"C:\Users\PC\PYTHON KAMP\6-weatherna.xlsx")# tabloyu jupitere yuklerken sikinti yasadik bundan dolayi konumunu tam vedik boylece sorunu cozmus olduk

In [111]:
weather_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [112]:
weather_df.head(3) # bastadaki 3 lu satiri getirdi

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0

In [113]:
weather_df.tail(4) # sondaki 4 lu satiri bize getirdi

   Istanbul  New York  Amsterdam  Paris
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [114]:
weather_df.info() # bize tablo ile ilgili genel bilgi verir

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Istanbul   8 non-null      float64
 1   New York   8 non-null      float64
 2   Amsterdam  8 non-null      float64
 3   Paris      6 non-null      float64
dtypes: float64(4)
memory usage: 420.0 bytes

In [115]:
weather_df.describe() # tablomuz ile ilgili genel istatistikleri bize veriri

        Istanbul   New York  Amsterdam      Paris
count   8.000000   8.000000   8.000000   6.000000
mean   21.625000  13.125000  16.750000  15.666667
std     3.814914   2.295181   2.712405   2.875181
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  11.500000  15.000000  14.250000
50%    21.500000  13.500000  15.500000  15.000000
75%    22.750000  15.000000  18.250000  17.250000
max    28.000000  16.000000  22.000000  20.000000

In [116]:
weather_df.count() # sayma yapar

Istanbul     8
New York     8
Amsterdam    8
Paris        6
dtype: int64

In [117]:
weather_df.isna() #  bos verileri bizim icin sayar

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False       True  False
2      True     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False      True      False   True
6     False     False      False  False
7     False     False      False   True
8     False     False      False   True

In [118]:
# KAYIP VERILERIN INCELENMESI

In [119]:
weather_na_df = pd.read_excel(r"C:\Users\PC\PYTHON KAMP\6-weatherna.xlsx")

In [120]:
weather_na_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [121]:
weather_na_df.isna()

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False       True  False
2      True     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False      True      False   True
6     False     False      False  False
7     False     False      False   True
8     False     False      False   True

In [122]:
weather_na_df.describe()

        Istanbul   New York  Amsterdam      Paris
count   8.000000   8.000000   8.000000   6.000000
mean   21.625000  13.125000  16.750000  15.666667
std     3.814914   2.295181   2.712405   2.875181
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  11.500000  15.000000  14.250000
50%    21.500000  13.500000  15.500000  15.000000
75%    22.750000  15.000000  18.250000  17.250000
max    28.000000  16.000000  22.000000  20.000000

In [123]:
weather_na_df.count()

Istanbul     8
New York     8
Amsterdam    8
Paris        6
dtype: int64

In [124]:
weather_na_df['Amsterdam'].count()

np.int64(8)

In [125]:
weather_na_df['Paris'].isna()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7     True
8     True
Name: Paris, dtype: bool

In [126]:
weather_na_df.dropna() # eger bir koluda kayip veri varsa o satiri direk gostermiyor cok kullanilan bir sey

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
6      15.0      12.0       15.0   15.0

In [127]:
weather_na_df.dropna(axis=1) # kolnu dusurursek geriye hicbir sey kalmiyor

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [128]:
weather_na_df.drop('Paris' ,axis=1)

   Istanbul  New York  Amsterdam
0      20.0      10.0       15.0
1      21.0      10.0        NaN
2       NaN      13.0       18.0
3      22.0      14.0       19.0
4      25.0      15.0       15.0
5      28.0       NaN       22.0
6      15.0      12.0       15.0
7      20.0      15.0       14.0
8      22.0      16.0       16.0

In [129]:
weather_na_df.fillna(20) # bos olan tum verileri geri doldurmamizi saglar

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0       20.0   14.0
2      20.0      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0      20.0       22.0   20.0
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0   20.0
8      22.0      16.0       16.0   20.0

In [130]:
weather_na_df.mean()

Istanbul     21.625000
New York     13.125000
Amsterdam    16.750000
Paris        15.666667
dtype: float64

In [131]:
weather_na_df.fillna(weather_na_df.mean()) # bo;lukari ortalamaya gore doldurmak istersek bu yontemi kullaniriz

   Istanbul  New York  Amsterdam      Paris
0    20.000    10.000      15.00  12.000000
1    21.000    10.000      16.75  14.000000
2    21.625    13.000      18.00  15.000000
3    22.000    14.000      19.00  18.000000
4    25.000    15.000      15.00  20.000000
5    28.000    13.125      22.00  15.666667
6    15.000    12.000      15.00  15.000000
7    20.000    15.000      14.00  15.666667
8    22.000    16.000      16.00  15.666667

In [132]:
weather_na_df.max()

Istanbul     28.0
New York     16.0
Amsterdam    22.0
Paris        20.0
dtype: float64

In [133]:
weather_na_df.min()

Istanbul     15.0
New York     10.0
Amsterdam    14.0
Paris        12.0
dtype: float64

In [134]:
## GROUP BY  KOMUTU

In [135]:
df = pd.read_csv('6-employee.csv')

In [136]:
df

   Department Employee  Salary  Experience           City
0   Marketing    Emp_1   53483           1       New York
1       Sales    Emp_2   78555           8         Austin
2     Finance    Emp_3   47159           3         Austin
3       Sales    Emp_4  110077           3  San Francisco
4       Sales    Emp_5   65920           1       New York
5          IT    Emp_6   97121          11        Chicago
6     Finance    Emp_7   99479           5        Chicago
7     Finance    Emp_8  119475          10       New York
8     Finance    Emp_9   49457           7        Chicago
9       Sales   Emp_10   96557          10        Chicago
10  Marketing   Emp_11  107189           9       New York
11    Finance   Emp_12  108953          12         Austin
12      Sales   Emp_13   82995           7       New York
13         IT   Emp_14   70757           9         Austin
14  Marketing   Emp_15   39692           8        Chicago
15         IT   Emp_16   75758          12        Chicago
16  Marketing   Emp_17  102409           2        Chicago
17      Sales   Emp_18  101211           1  San Francisco
18         HR   Emp_19   95697           7         Austin
19  Marketing   Emp_20   67065           7  San Francisco
20         IT   Emp_21   62606          14  San Francisco
21      Sales   Emp_22   41534           8       New York
22  Marketing   Emp_23   70397           5  San Francisco
23         HR   Emp_24   31016           3       New York
24         HR   Emp_25  119789          12       New York
25    Finance   Emp_26   85591           8  San Francisco
26    Finance   Emp_27  119812           6         Austin
27         IT   Emp_28   53247          11         Austin
28  Marketing   Emp_29   54300           3         Austin
29  Marketing   Emp_30  104065           1         Austin
30    Finance   Emp_31  112798           3         Austin
31  Marketing   Emp_32   39268           5  San Francisco
32  Marketing   Emp_33  116807          14  San Francisco
33         HR   Emp_34   42185           3        Chicago
34    Finance   Emp_35   93704           1         Austin
35      Sales   Emp_36  116779           5  San Francisco
36    Finance   Emp_37   69099          10        Chicago
37      Sales   Emp_38   38571           7         Austin
38         HR   Emp_39   68044          14       New York
39         IT   Emp_40   81214           7        Chicago
40  Marketing   Emp_41   91228          11  San Francisco
41         HR   Emp_42   78984           9       New York
42  Marketing   Emp_43   70774          10       New York
43         IT   Emp_44   32568          10       New York
44         IT   Emp_45   92592          12        Chicago
45         HR   Emp_46   97563          13  San Francisco
46         IT   Emp_47   32695           3       New York
47      Sales   Emp_48   78190           7         Austin
48         IT   Emp_49   35258           1       New York
49  Marketing   Emp_50  117538           4       New York

In [137]:
df.describe()

              Salary  Experience
count      50.000000   50.000000
mean    78344.500000    7.060000
std     27817.603904    3.966235
min     31016.000000    1.000000
25%     53687.250000    3.000000
50%     78769.500000    7.000000
75%    100778.000000   10.000000
max    119812.000000   14.000000

In [138]:
df.mean() # mean yaptigimiz zaman anlamiyor tek tek istersek bizim icin mean bulur

TypeError: Could not convert ['MarketingSalesFinanceSalesSalesITFinanceFinanceFinanceSalesMarketingFinanceSalesITMarketingITMarketingSalesHRMarketingITSalesMarketingHRHRFinanceFinanceITMarketingMarketingFinanceMarketingMarketingHRFinanceSalesFinanceSalesHRITMarketingHRMarketingITITHRITSalesITMarketing'
 'Emp_1Emp_2Emp_3Emp_4Emp_5Emp_6Emp_7Emp_8Emp_9Emp_10Emp_11Emp_12Emp_13Emp_14Emp_15Emp_16Emp_17Emp_18Emp_19Emp_20Emp_21Emp_22Emp_23Emp_24Emp_25Emp_26Emp_27Emp_28Emp_29Emp_30Emp_31Emp_32Emp_33Emp_34Emp_35Emp_36Emp_37Emp_38Emp_39Emp_40Emp_41Emp_42Emp_43Emp_44Emp_45Emp_46Emp_47Emp_48Emp_49Emp_50'
 'New YorkAustinAustinSan FranciscoNew YorkChicagoChicagoNew YorkChicagoChicagoNew YorkAustinNew YorkAustinChicagoChicagoChicagoSan FranciscoAustinSan FranciscoSan FranciscoNew YorkSan FranciscoNew YorkNew YorkSan FranciscoAustinAustinAustinAustinAustinSan FranciscoSan FranciscoChicagoAustinSan FranciscoChicagoAustinNew YorkChicagoSan FranciscoNew YorkNew YorkNew YorkChicagoSan FranciscoNew YorkAustinNew YorkNew York'] to numeric

In [ ]:
df.count()

In [ ]:
df.info()

In [ ]:
df[df['Experience'] > 6].count()

In [ ]:
df.head()

In [ ]:
df_group = df.groupby('Department')

In [ ]:
df_group.count()

In [ ]:
df_group.describe()

In [ ]:
df_group.info() # groupby kullandigimiz tabloya info kodunu kullanmayiz cunku zaten belli bir kaliba gore gurupladik

In [ ]:
df_group['Salary'].count()

In [ ]:
df_sehir = df.groupby('City')

In [ ]:
df_sehir.count()

In [ ]:
df_sehir['Salary'].count()

In [ ]:
df_sehir['Salary'].mean()

In [ ]:
## CONCAT ( birlestirme)

In [ ]:
df1  = pd.read_csv(r"C:\Users\PC\PYTHON KAMP\7-concat_data1.csv")

In [ ]:
df1

In [ ]:
df2 =  pd.read_csv(r"C:\Users\PC\PYTHON KAMP\7-concat_data2.csv")

In [ ]:
df2

In [ ]:
df_concat = pd.concat([df1,df2], ignore_index=True) # ignore_index = True yaptik cunku 2 veriyi birlestirik ve id lerin birbirini takip etmesini istedik

In [ ]:
df_concat

In [ ]:
# MERGE ( tablolari birlestirmek icin merge komutunu daha cok kullaniriz bu daha onemli bir komut

In [ ]:
df_merge1 = pd.read_csv(r"C:\Users\PC\PYTHON KAMP\7-merge_data1.csv")

In [ ]:
df_merge2 = pd.read_csv(r"C:\Users\PC\PYTHON KAMP\7-merge_data2.csv")

In [ ]:
df_merge1

In [ ]:
df_merge2 # goruldugu uzere id ler arasinda bir karmasa bunla alakai neler yapabilriz asagida gostericez

In [ ]:
# merge - outer join ( her iki tabloyu direk birlestirmemiz saglar bize )

In [ ]:
df_merge_outer = pd.merge(df_merge1, df_merge2, on= "Employee_ID", how = "outer")

In [ ]:
df_merge_outer

In [ ]:
# merge - left join ( ilk tablodaki herseyi al ve 2. tablodaki eslesenleri al )  seklinde kullnariiz

In [ ]:
df_merge_left = pd.merge(df_merge1,df_merge2, on="Employee_ID", how="left")

In [ ]:
df_merge_left

In [ ]:
# merge - right join ( 2. tablonun tamamini al 1. tablodan eslesenleri getir seklinde calisir bu kodda )

In [ ]:
df_merge_right = pd.merge(df_merge1,df_merge2, on="Employee_ID", how="right")

In [ ]:
df_merge_left

In [ ]:
# merge- inner join ( her 2 tablodada sadece kesisenleri alir bu kodumuzda )

In [ ]:
df_merge_inner = pd.merge(df_merge1,df_merge2, on="Employee_ID", how="inner")

In [ ]:
df_merge_inner

In [ ]:
#APPLY

In [143]:
df = pd.read_csv(r"C:\Users\PC\PYTHON KAMP\8-apply_function_data.csv")

In [144]:
df

    Employee_ID     Name Department  Salary  Experience  Performance_Score
0             1    Emp_1  Marketing   82251           6                  5
1             2    Emp_2      Sales   52662          24                  3
2             3    Emp_3    Finance   38392           5                  3
3             4    Emp_4      Sales   60535          20                  3
4             5    Emp_5      Sales  108603           2                  2
..          ...      ...        ...     ...         ...                ...
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

[100 rows x 6 columns]

In [145]:
df.head()

   Employee_ID   Name Department  Salary  Experience  Performance_Score
0            1  Emp_1  Marketing   82251           6                  5
1            2  Emp_2      Sales   52662          24                  3
2            3  Emp_3    Finance   38392           5                  3
3            4  Emp_4      Sales   60535          20                  3
4            5  Emp_5      Sales  108603           2                  2

In [146]:
df.describe()

       Employee_ID         Salary  Experience  Performance_Score
count   100.000000     100.000000  100.000000          100.00000
mean     50.500000   77508.090000   12.090000            3.03000
std      29.011492   26083.327596    7.543939            1.41746
min       1.000000   30206.000000    1.000000            1.00000
25%      25.750000   54347.500000    5.000000            2.00000
50%      50.500000   80932.000000   12.000000            3.00000
75%      75.250000   97620.500000   19.000000            4.00000
max     100.000000  119474.000000   24.000000            5.00000

In [147]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        100 non-null    int64
 1   Name               100 non-null    object
 2   Department         100 non-null    object
 3   Salary             100 non-null    int64
 4   Experience         100 non-null    int64
 5   Performance_Score  100 non-null    int64
dtypes: int64(4), object(2)
memory usage: 4.8+ KB

In [148]:
df.max()

Employee_ID             100
Name                 Emp_99
Department            Sales
Salary               119474
Experience               24
Performance_Score         5
dtype: object

In [149]:
df.min()

Employee_ID                1
Name                   Emp_1
Department           Finance
Salary                 30206
Experience                 1
Performance_Score          1
dtype: object

In [150]:
df.columns

Index(['Employee_ID', 'Name', 'Department', 'Salary', 'Experience',
       'Performance_Score'],
      dtype='object')

In [151]:
df[1:20]

    Employee_ID    Name Department  Salary  Experience  Performance_Score
1             2   Emp_2      Sales   52662          24                  3
2             3   Emp_3    Finance   38392           5                  3
3             4   Emp_4      Sales   60535          20                  3
4             5   Emp_5      Sales  108603           2                  2
5             6   Emp_6         IT   82256           6                  5
6             7   Emp_7    Finance  119135          22                  1
7             8   Emp_8    Finance   65222          11                  4
8             9   Emp_9    Finance  107373          16                  1
9            10  Emp_10      Sales  109575          16                  5
10           11  Emp_11  Marketing  114651           1                  4
11           12  Emp_12    Finance   93335           9                  5
12           13  Emp_13      Sales   40965           6                  3
13           14  Emp_14         IT   54538          16                  4
14           15  Emp_15  Marketing  100592           3                  3
15           16  Emp_16         IT   38110          20                  1
16           17  Emp_17  Marketing  109309           4                  1
17           18  Emp_18      Sales   57266          19                  4
18           19  Emp_19         HR   82992           3                  4
19           20  Emp_20  Marketing  112948          19                  5

In [152]:
# bir kolan daha ekleyelim ve maasi 50000 den dusuk 50.000 ile 80.000 arasinda ise ortalama ve 80.000 den yukse yuksek maas seklinde yeni bir kolan ekleyelim tablomuza

In [153]:
def salary_category(salary):
    if salary < 50000:
        return"low maas"
    elif 50000 <= salary < 80000:
        return"ortalama maas"
    else:
        return"yuksek maas"

In [154]:
salary_category

In [155]:
df["salary category"] = df["Salary"].apply(salary_category) # seklinde tablomuza yeni bir veri eklemis olduk

In [156]:
df # salart kategorisi

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,salary category
0,1,Emp_1,Marketing,82251,6,5,yuksek maas
1,2,Emp_2,Sales,52662,24,3,ortalama maas
2,3,Emp_3,Finance,38392,5,3,low maas
3,4,Emp_4,Sales,60535,20,3,ortalama maas
4,5,Emp_5,Sales,108603,2,2,yuksek maas
...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,yuksek maas
96,97,Emp_97,Sales,100467,22,2,yuksek maas
97,98,Emp_98,IT,82662,23,3,yuksek maas
98,99,Emp_99,IT,42688,22,1,low maas
99,100,Emp_100,HR,55342,14,3,ortalama maas

In [157]:
# yeni bir performasn skoru olustur calisanin tecrubesi 10 yildan fazla ise performence skoru 1 yil arttir

In [158]:
def adjust_performance(experince):
    if experince > 10 :
        return 1 
    else:
        return 0

In [159]:
df["Adjusted"] = df["Experience"].apply(adjust_performance)

In [160]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,salary category,Adjusted
0,1,Emp_1,Marketing,82251,6,5,yuksek maas,0
1,2,Emp_2,Sales,52662,24,3,ortalama maas,1
2,3,Emp_3,Finance,38392,5,3,low maas,0
3,4,Emp_4,Sales,60535,20,3,ortalama maas,1
4,5,Emp_5,Sales,108603,2,2,yuksek maas,0
...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,yuksek maas,1
96,97,Emp_97,Sales,100467,22,2,yuksek maas,1
97,98,Emp_98,IT,82662,23,3,yuksek maas,1
98,99,Emp_99,IT,42688,22,1,low maas,1
99,100,Emp_100,HR,55342,14,3,ortalama maas,1

In [161]:
df["newscore"] = df["Performance_Score"] + df["Adjusted"]

In [162]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,salary category,Adjusted,newscore
0,1,Emp_1,Marketing,82251,6,5,yuksek maas,0,5
1,2,Emp_2,Sales,52662,24,3,ortalama maas,1,4
2,3,Emp_3,Finance,38392,5,3,low maas,0,3
3,4,Emp_4,Sales,60535,20,3,ortalama maas,1,4
4,5,Emp_5,Sales,108603,2,2,yuksek maas,0,2
...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,yuksek maas,1,5
96,97,Emp_97,Sales,100467,22,2,yuksek maas,1,3
97,98,Emp_98,IT,82662,23,3,yuksek maas,1,4
98,99,Emp_99,IT,42688,22,1,low maas,1,2
99,100,Emp_100,HR,55342,14,3,ortalama maas,1,4

In [163]:
# 2. cozum yolu

In [170]:
def  adjust_new(row):
    if row["Experience"] > 10:
        return row["Performance_Score"] + 1 
    else:
        return row["Performance_Score"]

In [171]:
df["Adjusted_Score"] = df.apply(adjust_new,axis=1)

In [172]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,salary category,Adjusted,newscore,Adjusted_Score
0,1,Emp_1,Marketing,82251,6,5,yuksek maas,0,5,5
1,2,Emp_2,Sales,52662,24,3,ortalama maas,1,4,4
2,3,Emp_3,Finance,38392,5,3,low maas,0,3,3
3,4,Emp_4,Sales,60535,20,3,ortalama maas,1,4,4
4,5,Emp_5,Sales,108603,2,2,yuksek maas,0,2,2
...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,yuksek maas,1,5,5
96,97,Emp_97,Sales,100467,22,2,yuksek maas,1,3,3
97,98,Emp_98,IT,82662,23,3,yuksek maas,1,4,4
98,99,Emp_99,IT,42688,22,1,low maas,1,2,2
99,100,Emp_100,HR,55342,14,3,ortalama maas,1,4,4

In [173]:
# eger isim kimsinda alt tire yerine bosluk gormek istersek ozaman asagidaki kodu kullanmamzi lazim olur

In [175]:
df["new_name"] = df["Name"].apply(lambda x : x.replace("_",""))

In [176]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,salary category,Adjusted,newscore,Adjusted_Score,new_name
0,1,Emp_1,Marketing,82251,6,5,yuksek maas,0,5,5,Emp1
1,2,Emp_2,Sales,52662,24,3,ortalama maas,1,4,4,Emp2
2,3,Emp_3,Finance,38392,5,3,low maas,0,3,3,Emp3
3,4,Emp_4,Sales,60535,20,3,ortalama maas,1,4,4,Emp4
4,5,Emp_5,Sales,108603,2,2,yuksek maas,0,2,2,Emp5
...,...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,yuksek maas,1,5,5,Emp96
96,97,Emp_97,Sales,100467,22,2,yuksek maas,1,3,3,Emp97
97,98,Emp_98,IT,82662,23,3,yuksek maas,1,4,4,Emp98
98,99,Emp_99,IT,42688,22,1,low maas,1,2,2,Emp99
99,100,Emp_100,HR,55342,14,3,ortalama maas,1,4,4,Emp100